"""
Step 3 (GQE) -- launch the external trainer as a subprocess.

Unlike the in-process Qiskit solvers, GQE runs the external repo's own
train.py in a separate process. That boundary is deliberate and explicit:
the external repo needs its own directory as the working directory for
Hydra config discovery, and it brings a different dependency stack.

This module imports nothing from either solver stack. It must stay
importable on a Qiskit-only install, because CLI dispatch imports it.

FOUR THINGS THIS DOES THAT A BARE subprocess CALL WOULD NOT
-----------------------------------------------------------
1. Verifies the checkout is patched before spending GPU time. Without the
   train_pipeline.py hunk the run succeeds and produces no parseable epoch
   log, which is the worst kind of failure -- expensive and silent.

2. Validates that the step 2 pickle belongs to the current molecule.

3. Generates configs/molecule/dmet_embedding.yaml at run time and also
   passes molecule.step2_pickle_path on the command line. The shipped
   version of that file had a hardcoded absolute path which silently
   pointed at a stale directory and produced plausible, meaningless
   results for an extended period.

4. Prepends the shim directory to PYTHONPATH so the external factory's
   top-level `import dmet_excitation_pool` resolves to the package's
   canonical implementation, without writing anything into the submodule.
"""

from __future__ import annotations

import os
import pickle
import subprocess
import sys
from pathlib import Path

__all__ = ["main", "build_command", "build_env"]

SHIM_DIR = Path(__file__).resolve().parent / "_gqe_shims"


def _shim_dir():
    if not SHIM_DIR.is_dir():
        raise FileNotFoundError(
            f"The GQE shim directory is missing: {SHIM_DIR}. The package "
            f"install is incomplete -- check that package_data includes "
            f"quantum/_gqe_shims/*.py."
        )
    return SHIM_DIR


def build_env(cfg, repo, base_env=None):
    """Environment for the training subprocess."""
    env = dict(base_env if base_env is not None else os.environ)

    # The shim directory first, so `import dmet_excitation_pool` resolves
    # to the package's implementation rather than any stale copy sitting in
    # the external checkout.
    existing = env.get("PYTHONPATH", "")
    parts = [str(_shim_dir())]
    if existing:
        parts.append(existing)
    env["PYTHONPATH"] = os.pathsep.join(parts)

    # Backend selection. The external repo never calls cudaq.set_target(),
    # so there is no Hydra key for this -- CUDA-Q reads it from the
    # environment itself.
    env.update(cfg.gqe.env_overlay())

    env.setdefault("GQE_QSCI_REPO_PATH", str(repo))
    return env


def build_command(cfg, repo, extra_args=None):
    """argv for train.py, including the mandatory Hydra overrides."""
    entry = Path(repo) / cfg.gqe.train_entrypoint
    if not entry.exists():
        raise FileNotFoundError(
            f"{cfg.gqe.train_entrypoint} not found in {repo}."
        )

    overrides = cfg.gqe.hydra_overrides(step2_pickle_path=cfg.step2_file)

    # Both of these are mandatory. Without molecule=..., train.py loads
    # configs/molecule/n2.yaml and trains on N2 while reporting your
    # molecule's numbers. Without a dmet_* pool spec, the stock pools try
    # to read a geometry the embedding does not have.
    joined = " ".join(overrides)
    if "molecule=" not in joined:
        raise RuntimeError("the molecule config override is missing")
    if "operator_pool.spec=" not in joined:
        raise RuntimeError("the operator_pool.spec override is missing")

    return [sys.executable, str(entry), *overrides, *(extra_args or [])]


def _write_molecule_config(repo, cfg):
    """
    Generate configs/molecule/<name>.yaml pointing at the current step 2
    pickle.

    Written fresh on every run rather than shipped, because a hardcoded
    path here is how a stale directory silently supplied the wrong
    embedding for an extended period. The command line also carries
    molecule.step2_pickle_path, so this is belt and braces.
    """
    conf_dir = Path(repo) / "configs" / "molecule"
    conf_dir.mkdir(parents=True, exist_ok=True)
    path = conf_dir / f"{cfg.gqe.molecule_config}.yaml"
    path.write_text(
        "# Generated by quenais.quantum.gqe_runner -- do not edit.\n"
        "# Regenerated on every run; the command line also passes\n"
        "# molecule.step2_pickle_path, which takes precedence.\n"
        "_target_: dmet_molecule_adapter.load_from_dmet_pickle\n"
        f"step2_pickle_path: {os.path.abspath(cfg.step2_file)}\n"
    )
    return path


def _preflight(cfg, repo):
    from quenais.quantum.gqe_setup import verify_gqe_repo

    if not os.path.exists(cfg.step2_file):
        raise FileNotFoundError(
            f"Run the embedding stage first: {cfg.step2_file} not found."
        )
    if not cfg.cached_result_is_current(cfg.step2_file, verbose=False):
        raise RuntimeError(
            f"{cfg.step2_file} was built for a different molecule or basis "
            f"than the config specifies ({cfg.molecule}/{cfg.basis}). "
            f"Re-run the embedding stage -- training on another system's "
            f"embedding produces a plausible number with no meaning."
        )

    with open(cfg.step2_file, "rb") as fh:
        step2 = pickle.load(fh)
    n_emb = step2.get("n_emb")

    problems = verify_gqe_repo(repo)
    if problems:
        raise RuntimeError(
            "The gqe-for-qsci checkout is not ready:\n  - "
            + "\n  - ".join(problems)
            + "\n\nFix with: quenais-gqe-setup --repo " + str(repo)
        )

    # Full FCI over the whole embedding space, purely for logging. Cost
    # grows combinatorially and becomes impractical above roughly 12-16
    # embedding orbitals -- and it runs BEFORE any training starts, so the
    # run appears to hang at the logger-construction step.
    keys = cfg.gqe.reference_keys or []
    if n_emb and n_emb > 14 and any("CASCI" in str(k) for k in keys):
        import warnings

        warnings.warn(
            f"reference_keys includes an R-CASCI entry and this embedding "
            f"has {n_emb} orbitals. That triggers a full FCI over the whole "
            f"embedding space for logging only, before training starts. Drop "
            f"it from cfg.gqe.reference_keys if the run stalls or exhausts "
            f"memory.",
            RuntimeWarning,
        )
    return step2


def main(cfg, force=False, extra_args=None):
    """
    Run GQE training.

    cfg   : quenais.config.Config
    force : rerun even if a log already exists
    """
    from quenais.quantum.gqe_setup import resolve_repo

    os.makedirs(cfg.results_dir, exist_ok=True)
    log_path = Path(cfg.gqe_log_file)

    if log_path.exists() and not force:
        print(f"[Step 3] GQE log already present: {log_path}")
        print("         Pass force=True to retrain.")
        return {"log_file": str(log_path), "skipped": True}

    repo = resolve_repo(cfg=cfg)
    step2 = _preflight(cfg, repo)

    _write_molecule_config(repo, cfg)
    cmd = build_command(cfg, repo, extra_args)
    env = build_env(cfg, repo)

    print(f"\n{'='*60}")
    print(f"[Step 3] GQE training -- {cfg.molecule}")
    print(f"{'='*60}")
    print(f"  repo     : {repo}")
    print(f"  embedding: {step2.get('n_emb')} orbitals "
          f"({2 * (step2.get('n_emb') or 0)} qubits)")
    print(f"  backend  : {cfg.gqe.cudaq_target}")
    print(f"  pool     : {cfg.gqe.operator_pool_spec}")
    print(f"  log      : {log_path}")
    print(f"  overrides: {' '.join(cmd[2:])}")
    print()

    with open(log_path, "w") as log:
        proc = subprocess.Popen(
            cmd, cwd=str(repo), env=env,
            stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
            text=True, bufsize=1,
        )
        epochs = 0
        for line in proc.stdout:
            print(line, end="")
            log.write(line)
            if line.startswith("[epoch "):
                epochs += 1
        proc.wait()

    if proc.returncode != 0:
        raise RuntimeError(
            f"train.py exited with code {proc.returncode}. See {log_path}."
        )

    if epochs == 0:
        # The train_pipeline.py patch emits these lines. Without it,
        # training succeeds and the visualisation stage has nothing to read.
        raise RuntimeError(
            f"Training finished but produced no '[epoch N] {{...}}' lines, "
            f"so there is nothing for the visualisation stage to parse. "
            f"This is the signature of a missing train_pipeline.py patch "
            f"hunk. Re-run: quenais-gqe-setup --repo {repo}"
        )

    print(f"\n[Step 3] Done -- {epochs} epochs logged to {log_path}")
    return {"log_file": str(log_path), "epochs": epochs, "skipped": False}
