#!/usr/bin/env python
"""
What ARE the determinants GQE selected?

Goes in: tools/inspect_gqe_determinants.py

WHY
---
At r=1.8 A the reported energy is 78.9371337895517 mHa across four runs using
TWO DIFFERENT operator pools -- identical to 15 significant figures. Different
pools produce different circuits and therefore different samples, so a result
that does not move at all is not being determined by the sampling.

Something is selecting the same 200 determinants regardless of input. This
script characterises that set so the mechanism is visible instead of guessed at.

The key view is the excitation-rank histogram: how many orbitals each
determinant differs by from the dominant configuration. The QiankunNet paper's
Fig 4a uses exactly this, and finds the important determinants sit at ranks 7-8
for [2Fe-2S]. If GQE's set is confined to low rank while the oracle's spreads
higher, the subspace is being restricted by construction -- which would explain
why it cannot move.
"""

from __future__ import annotations

import argparse
import sys
from collections import Counter
from pathlib import Path

import numpy as np

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))


def excitation_rank(idx, space, ref_a, ref_b):
    """Orbitals differing from the reference, counted over both spins."""
    a, b = space.strings(np.atleast_1d(idx))
    out = []
    for aa, bb in zip(np.atleast_1d(a), np.atleast_1d(b)):
        da = bin(int(aa) ^ int(ref_a)).count("1") // 2
        db = bin(int(bb) ^ int(ref_b)).count("1") // 2
        out.append(da + db)
    return np.asarray(out)


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--r", type=float, required=True)
    p.add_argument("--dets", required=True)
    p.add_argument("--atoms", nargs=2, default=("N", "N"))
    p.add_argument("--basis", default="sto-3g")
    p.add_argument("--ncas", type=int, default=8)
    p.add_argument("--nelecas", type=int, default=10)
    args = p.parse_args()

    sys.path.insert(0, str(REPO / "tools"))
    from run_correlation_scan import build_cas_molecule
    from compare_gqe_determinants import strings_to_indices
    try:
        from quenais.quantum import det_analysis as da
    except ImportError:
        import det_analysis as da

    mol, _, _, _ = build_cas_molecule(
        tuple(args.atoms), args.r, args.basis, args.ncas, args.nelecas)
    e_exact, flat, space = da.casci_vector(mol)
    order, _ = da.weight_curve(flat)
    w = flat ** 2

    d = np.load(args.dets)
    gqe_idx = strings_to_indices(d["strs"], int(d["norb"]),
                                 tuple(int(x) for x in d["nelec"]), space)
    n = len(gqe_idx)
    oracle_idx = order[:n]

    # Reference = the dominant determinant of the exact wavefunction.
    ref_a, ref_b = space.strings(int(order[0]))
    ref_a, ref_b = int(np.atleast_1d(ref_a)[0]), int(np.atleast_1d(ref_b)[0])

    rank_g = excitation_rank(gqe_idx, space, ref_a, ref_b)
    rank_o = excitation_rank(oracle_idx, space, ref_a, ref_b)
    rank_all = excitation_rank(np.arange(space.ndet), space, ref_a, ref_b)

    print(f"\n  N2  r = {args.r:.4f} A   ndet={space.ndet}   selected={n}")
    print(f"  reference determinant = index {int(order[0])} "
          f"(weight {float(w[order[0]]):.6f})\n")

    print(f"  excitation rank   GQE   oracle   available   "
          f"weight in rank (exact)")
    cg, co, ca = Counter(rank_g), Counter(rank_o), Counter(rank_all)
    for k in sorted(set(list(cg) + list(co) + list(ca))):
        mask = rank_all == k
        wk = float(w[mask].sum())
        print(f"  {k:>15}  {cg.get(k,0):>5}  {co.get(k,0):>7}  "
              f"{ca.get(k,0):>10}   {wk:>12.8f}")

    print(f"\n  weight captured: GQE {float(w[gqe_idx].sum()):.8f}   "
          f"oracle {float(w[oracle_idx].sum()):.8f}")

    # Which high-weight determinants did GQE miss, and what rank are they?
    missing = [i for i in oracle_idx.tolist() if i not in set(gqe_idx.tolist())]
    if missing:
        miss = np.asarray(missing)
        mw = w[miss]
        top = miss[np.argsort(mw)[::-1][:10]]
        print(f"\n  GQE missed {len(missing)} of the oracle's {n}. "
              f"The ten heaviest:")
        print(f"  {'index':>8} {'weight':>12} {'rank':>6}")
        for i in top:
            rk = int(excitation_rank(int(i), space, ref_a, ref_b)[0])
            print(f"  {int(i):>8} {float(w[i]):>12.8f} {rk:>6}")
        print(f"\n  total weight missed: {float(w[miss].sum()):.8f}")

    # Is GQE's set closed under the spin-completion the QSCI code applies?
    # If it is exactly closed, the set was generated by that completion rather
    # than by sampling -- which would explain why changing the pool changes
    # nothing.
    print(f"\n  rank spread: GQE {rank_g.min()}-{rank_g.max()}   "
          f"oracle {rank_o.min()}-{rank_o.max()}")


if __name__ == "__main__":
    main()