#!/usr/bin/env python
"""
Does completing the spatial symmetry orbits rescue GQE's determinant set?

Goes in: tools/test_symmetry_completion.py

THE HYPOTHESIS
--------------
At r=1.8 A, GQE's 200 determinants capture 76.9% of the wavefunction and give
78.9 mHa. The determinants it missed come in pairs and quadruples of IDENTICAL
weight -- symmetry partners. It holds some members of each degenerate orbit and
not the others.

A determinant set that breaks a symmetry orbit cannot represent a symmetric
wavefunction, however good the rest of the set is. That would explain the error,
and it would explain why four runs with two different operator pools produced
bit-identical energies: the QSCI code's enlarge() step completes SPIN multiplets
(generate_group_for_totalspin_symmetry enumerates spin reassignments on
open-shell orbitals) but nothing completes SPATIAL degeneracy, so no amount of
different sampling repairs it.

This script tests that offline, without touching the vendored repo: take the
dumped determinants, close them under the Hamiltonian's orbital symmetries,
re-diagonalise, and see what comes back.

HOW SYMMETRY IS DETECTED
------------------------
No point-group labels are needed, which matters because a DMET embedding basis
has none. Two orbitals are equivalent if swapping them leaves h1 and h2
invariant -- that is checked directly against the integrals. It therefore works
for any Hamiltonian this pipeline produces, embedding or not.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))


def find_symmetry_transpositions(h1, h2, tol=1e-8):
    """Orbital pairs whose exchange leaves the Hamiltonian invariant."""
    n = h1.shape[0]
    pairs = []
    for p in range(n):
        for q in range(p + 1, n):
            perm = list(range(n))
            perm[p], perm[q] = q, p
            if not np.allclose(h1[np.ix_(perm, perm)], h1, atol=tol, rtol=0):
                continue
            if not np.allclose(h2[np.ix_(perm, perm, perm, perm)], h2,
                               atol=tol, rtol=0):
                continue
            pairs.append((p, q))
    return pairs


def _swap_bits(x, p, q):
    bp = (x >> p) & 1
    bq = (x >> q) & 1
    if bp == bq:
        return x
    return x ^ (1 << p) ^ (1 << q)


def complete_orbits(strs, pairs, cap=None):
    """
    Close a determinant set under the given orbital transpositions.

    Breadth-first over the group generated by the transpositions, so whole
    orbits come in rather than arbitrary fragments of them.
    """
    seen = {(int(a), int(b)) for a, b in strs}
    frontier = list(seen)
    while frontier:
        new = []
        for a, b in frontier:
            for p, q in pairs:
                key = (_swap_bits(a, p, q), _swap_bits(b, p, q))
                if key not in seen:
                    seen.add(key)
                    new.append(key)
                    if cap and len(seen) >= cap:
                        return seen
        frontier = new
    return seen


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--r", type=float, required=True)
    p.add_argument("--dets", required=True)
    p.add_argument("--atoms", nargs=2, default=("N", "N"))
    p.add_argument("--basis", default="sto-3g")
    p.add_argument("--ncas", type=int, default=8)
    p.add_argument("--nelecas", type=int, default=10)
    args = p.parse_args()

    sys.path.insert(0, str(REPO / "tools"))
    from run_correlation_scan import build_cas_molecule
    from compare_gqe_determinants import strings_to_indices
    try:
        from quenais.quantum import det_analysis as da
    except ImportError:
        import det_analysis as da

    from pyscf.fci import cistring

    mol, _, _, _ = build_cas_molecule(
        tuple(args.atoms), args.r, args.basis, args.ncas, args.nelecas)
    e_exact, flat, space = da.casci_vector(mol)
    order, _ = da.weight_curve(flat)
    w = flat ** 2

    h = mol.cas_hamiltonian
    pairs = find_symmetry_transpositions(np.asarray(h.h1), np.asarray(h.h2))
    print(f"\n  N2  r = {args.r:.4f} A   ncas={space.norb}   ndet={space.ndet}")
    print(f"  symmetry-equivalent orbital pairs found: {pairs if pairs else 'none'}")
    if not pairs:
        print("  No orbital degeneracy detected -- this cannot be the cause here.")
        return

    d = np.load(args.dets)
    strs = [(int(a), int(b)) for a, b in d["strs"]]
    gqe_idx = strings_to_indices(d["strs"], int(d["norb"]),
                                 tuple(int(x) for x in d["nelec"]), space)
    n = len(gqe_idx)

    completed = complete_orbits(strs, pairs)
    comp_idx = np.array(sorted(
        cistring.str2addr(space.norb, space.nelec[0], a) * space.nb
        + cistring.str2addr(space.norb, space.nelec[1], b)
        for a, b in completed), dtype=np.int64)

    e_gqe = da.projected_energy(mol, gqe_idx, space=space)
    e_comp = da.projected_energy(mol, comp_idx, space=space)
    e_orc = da.projected_energy(mol, order[:n], space=space)
    e_orc_big = da.projected_energy(mol, order[:len(comp_idx)], space=space)

    print(f"\n  {'set':<22} {'dets':>6} {'weight':>12} {'error (mHa)':>13}")
    print(f"  {'GQE as sampled':<22} {n:>6} {float(w[gqe_idx].sum()):>12.8f} "
          f"{1e3*(e_gqe-e_exact):>13.4f}")
    print(f"  {'GQE + orbit closure':<22} {len(comp_idx):>6} "
          f"{float(w[comp_idx].sum()):>12.8f} {1e3*(e_comp-e_exact):>13.4f}")
    print(f"  {'oracle, same count':<22} {n:>6} "
          f"{float(w[order[:n]].sum()):>12.8f} {1e3*(e_orc-e_exact):>13.4f}")
    print(f"  {'oracle, matched size':<22} {len(comp_idx):>6} "
          f"{float(w[order[:len(comp_idx)]].sum()):>12.8f} "
          f"{1e3*(e_orc_big-e_exact):>13.4f}")

    print(f"\n  VERDICT")
    err_c = 1e3 * (e_comp - e_exact)
    err_g = 1e3 * (e_gqe - e_exact)
    grew = len(comp_idx) / n
    if err_c < err_g / 10:
        print(f"    CONFIRMED. Closing the symmetry orbits takes {err_g:.4f} ->")
        print(f"    {err_c:.4f} mHa for {grew:.2f}x the determinants. The set was")
        print(f"    never bad -- it was incomplete. Fix belongs in the QSCI")
        print(f"    subspace construction, not in the sampler.")
    elif err_c < err_g / 2:
        print(f"    PARTIAL. {err_g:.4f} -> {err_c:.4f} mHa. Symmetry breaking is")
        print(f"    part of the problem but not all of it.")
    else:
        print(f"    NOT THE CAUSE. {err_g:.4f} -> {err_c:.4f} mHa. The missing")
        print(f"    determinants are not merely symmetry partners; look")
        print(f"    elsewhere.")


if __name__ == "__main__":
    main()